version: '3.7'

services:
  react-app:
    container_name: react-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - './src:/app/src'
    ports:
      - 1337:3000
    environment:
      - WATCHPACK_POLLING=true
